# Generated by Django 5.2.9 on 2026-04-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Mon Site E-commerce', max_length=100)),
                ('slogan', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(default='EUR', max_length=10)),
            ],
            options={
                'verbose_name': 'Paramètres du Site',
                'verbose_name_plural': 'Paramètres du Site',
            },
        ),
    ]
