# Generated by Django 5.2.9 on 2026-04-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0002_team_sitesettings_copyright_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Photo de bannière'),
        ),
    ]
