# Generated by Django 5.2.9 on 2026-04-03 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0003_sitesettings_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='banner',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='banner_desckop',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Photo de bannière Desktop'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='banner_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Photo de bannière Mobile'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='banner_sub_title',
            field=models.TextField(blank=True, default='Sous-titre banner', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='banner_title',
            field=models.TextField(blank=True, default='Titre banner', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='main_objective',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Leur objectif'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mission_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description de la Mission'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_summary',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Résumé du service/produit'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='since_year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Année de début'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='target_audience',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Public cible'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='values_text',
            field=models.TextField(blank=True, help_text='Séparez les valeurs par un retour à la ligne.', null=True, verbose_name='Nos Valeurs'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vision_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description de la Vision'),
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Année')),
                ('title', models.CharField(max_length=150, verbose_name="Titre de l'étape")),
                ('description', models.TextField(verbose_name="Description de l'événement")),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web_site.sitesettings')),
            ],
            options={
                'verbose_name': 'Étape du parcours',
                'verbose_name_plural': 'Étapes du parcours',
                'ordering': ['order', 'year'],
            },
        ),
    ]
