# Generated by Django 5.2.9 on 2026-04-03 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0004_remove_sitesettings_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='team',
        ),
        migrations.AddField(
            model_name='teammember',
            name='site_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='web_site.sitesettings'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
