# Generated by Django 3.2.25 on 2026-03-30 05:18

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_has_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_size',
        ),
        migrations.AddField(
            model_name='product',
            name='has_variants',
            field=models.BooleanField(default=False, verbose_name='Ce produit a des variantes (Prix/Modèles multiples)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par défaut (MGA)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(verbose_name='Stock par défaut'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=100, verbose_name='Nom de la variante (ex: Rose / 120p)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix spécifique (MGA)')),
                ('stock', models.IntegerField(verbose_name='Stock de cette variante')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=None, size=[800, 800], upload_to='photos/variants', verbose_name='Image spécifique')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
        ),
    ]
