# Generated by Django 3.2.25 on 2026-03-30 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20260330_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_variants',
        ),
        migrations.AddField(
            model_name='product',
            name='group_id',
            field=models.CharField(blank=True, help_text="Identifiant commun (ex: 'CUTTER-DELUXE') pour lier les variantes entre elles.", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_main_representative',
            field=models.BooleanField(default=False, verbose_name='Afficher cet article en priorité dans le catalogue'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_label',
            field=models.CharField(blank=True, help_text="Ce qui différencie cet article des autres (ex: 'Rouge', 'Pack de 10', 'Format A4').", max_length=100),
        ),
        migrations.AlterField(
            model_name='reviewandrating',
            name='rating',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='reviewandrating',
            name='review',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
