# Generated by Django 3.2.25 on 2026-03-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20260330_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='group_id',
            field=models.CharField(blank=True, help_text="ID commun pour lier les variantes (ex: 'CUTTER-001').", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_main_representative',
            field=models.BooleanField(default=False, verbose_name='Afficher en priorité dans le catalogue'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (MGA)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_point',
            field=models.IntegerField(default=5, verbose_name='Seuil Critique'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(verbose_name='Stock disponible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant_label',
            field=models.CharField(blank=True, help_text="Ex: 'Rouge', 'Bleu', 'XL'.", max_length=100),
        ),
    ]
