# Generated by Django 3.2.25 on 2026-04-02 08:15

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20260330_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[800, 800], upload_to='photos/products', verbose_name='Image Principale'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[800, 800], upload_to='photos/product_gallery', verbose_name='Image Additionnelle'),
        ),
    ]
